# Generated by Django 5.0.3 on 2024-03-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_relatedpost_post_related_posts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relatedpost',
            constraint=models.UniqueConstraint(models.F('main_post'), models.F('related_post'), name='unique_mainpost_relatedpost'),
        ),
    ]
