# Generated by Django 5.0.3 on 2024-03-25 11:52

from django.db import migrations
from ..models import Post, Category


def copy_categories(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    Category = apps.get_model("blog", "Category")
    for post in Post.objects.all():
        post.category_new = Category.objects.get(category__icontains=post.category)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_category_options_post_category_new"),
    ]

    operations = [migrations.RunPython(copy_categories)]
